Feature make token non transferable
Azuro-protocol/Access pull request #14
Opened 2023-02-15 17:58 UTC by KiselevMaxim

2023-02-15 19:32 UTC, DenisKaizer approved these changes

2023-02-16 05:58 UTC, Shchepetov requested changes

2023-02-16 05:58 UTC, Shchepetov commented on contracts/Access.sol
> +        bool isNonTransferable
It is better to avoid negations in variable names and logical expressions
Anyway in Solidity you cannot set the default value of the argument

2023-02-16 05:58 UTC, Shchepetov commented on contracts/Access.sol
> +            revert NoChanges();
it will be very disappointing to get this error when calling `changeBatchTokenTransferability `

2023-02-16 05:58 UTC, Shchepetov commented on contracts/Access.sol
> +        emit TokenTransferabilityChanged(
That's not cool to emit events in the loop so in my opinion there should be special event for batch transferability changes

2023-02-16 08:30 UTC, KiselevMaxim commented on contracts/Access.sol
> +        bool isNonTransferable
Yes, I know, but such a name is expressive and reveals the essence of the variable. 
This feature name is `nonTransferable` and by default it is not set, only at some scenario it is needed to be set, and when it set `true` is non transferable.

2023-02-16 08:44 UTC, KiselevMaxim commented on contracts/Access.sol
> +        emit TokenTransferabilityChanged(
Event emits in function `_changeTokenTransferability()` that makes one token change. It is done for code simplicity.

2023-02-16 09:03 UTC, KiselevMaxim commented on contracts/Access.sol
> +            revert NoChanges();
Modified `NoChanges` - added token id in [9b26d69](https://github.com/Azuro-protocol/Access/pull/14/commits/9b26d69d643e4631c641a1644af5dda0d2716e6d)

2023-02-16 09:14 UTC, Shchepetov commented on contracts/Access.sol
> +        bool isNonTransferable
Anyway there are no default value for tokens and there is no difference between set tokens as "nonTransferable" or "transferable"

2023-02-16 09:14 UTC, Shchepetov commented on contracts/Access.sol
> +            revert NoChanges();
Maybe remove this error?

2023-02-16 09:16 UTC, Shchepetov commented on contracts/Access.sol
> +        emit TokenTransferabilityChanged(
It's not optimal for gas consumption. You can move event emitting to external methods

2023-02-16 10:02 UTC, KiselevMaxim commented on contracts/Access.sol
> +        bool isNonTransferable
The point is that, by default tokens are transferable, and this PR is making restriction for transfer ability.

2023-02-16 10:04 UTC, KiselevMaxim commented on contracts/Access.sol
> +            revert NoChanges();
I prefer to revert such error

2023-02-16 10:16 UTC, KiselevMaxim commented on contracts/Access.sol
> +        emit TokenTransferabilityChanged(
In my opinion, non transferable feature is not common case and batch changing is rarer. So batch changing transferability in scenario with 2-3 tokens is not much gas difference between one event with 2-3 tokens in it and 2-3 events

2023-02-17 12:29 UTC, KiselevMaxim commented on contracts/Access.sol
> +        emit TokenTransferabilityChanged(
added separate batch event [9ac0577](https://github.com/Azuro-protocol/Access/pull/14/commits/9ac05771bf3b6d92a294cccddca8b408fd8fb827)

2023-02-19 21:42 UTC, maximtim requested changes

2023-02-19 21:42 UTC, maximtim commented on README.md
> +#### 4. Owner grants role (mint NFT) to user, isNonTransferablefalse = false
isNonTransferablefalse typo

2023-02-19 21:42 UTC, maximtim commented on contracts/Access.sol
> +        TokenTransferability memory tokens
`token` is single here, so probably remove `-s`

2023-02-19 21:51 UTC, KiselevMaxim commented on README.md
> +#### 4. Owner grants role (mint NFT) to user, isNonTransferablefalse = false
fixed

2023-02-19 21:51 UTC, KiselevMaxim commented on contracts/Access.sol
> +        TokenTransferability memory tokens
Yes, correct, fixed

2023-02-20 08:41 UTC, maximtim approved these changes

2024-02-06 19:11 UTC, Shchepetov approved these changes

2024-02-14 21:08 UTC, closed without merging